/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as addDinner from "../addDinner";
import type * as addGuest from "../addGuest";
import type * as lib_attendance from "../lib/attendance";
import type * as lib_getUser from "../lib/getUser";
import type * as lib_migrations from "../lib/migrations";
import type * as storeUser from "../storeUser";
import type * as types from "../types";
import type * as updateGuest from "../updateGuest";
import type * as updateGuestPrefs from "../updateGuestPrefs";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  addDinner: typeof addDinner;
  addGuest: typeof addGuest;
  "lib/attendance": typeof lib_attendance;
  "lib/getUser": typeof lib_getUser;
  "lib/migrations": typeof lib_migrations;
  storeUser: typeof storeUser;
  types: typeof types;
  updateGuest: typeof updateGuest;
  updateGuestPrefs: typeof updateGuestPrefs;
}>;
