/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.1.6.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import { GenericSchema, SchemaDefinition, TableDefinition } from "convex/schema";
import { DataModel } from "../schema";

export type { DataModel };
